project_id = "vecdjxbrkaqpvftwoafj"

[functions.generate-roadmap]
verify_jwt = false

[functions.recommend-content]
verify_jwt = true

[functions.send-login-alert]
verify_jwt = false

[functions.send-chat-otp]
verify_jwt = false